CampusV4/Controllers/InquiryCostEstimateController.cs
using CampusV4.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Script.Serialization;

namespace CampusV4.Controllers
{
    public class InquiryCostEstimateController : Controller
    {


        // GET: InquiryCostEstimate
        public ActionResult Index()
        {
            var model = new InquiryCostEstimateViewModel();
            // 分類記号
            var ClassificationdataList = new List<InguiryCostEstimate_ClassificationData>();
            ClassificationdataList.Add(new InguiryCostEstimate_ClassificationData("　", ""));
            ClassificationdataList.Add(new InguiryCostEstimate_ClassificationData("A", "半導体金型・部品"));
            ClassificationdataList.Add(new InguiryCostEstimate_ClassificationData("B", "Chase Holder"));
            ClassificationdataList.Add(new InguiryCostEstimate_ClassificationData("C", "Kit"));
            ClassificationdataList.Add(new InguiryCostEstimate_ClassificationData("D", "装置ユニット・装置部品"));
            ClassificationdataList.Add(new InguiryCostEstimate_ClassificationData("E", "打抜金型・部品"));
            ClassificationdataList.Add(new InguiryCostEstimate_ClassificationData("G", "LED金型・部品"));
            ClassificationdataList.Add(new InguiryCostEstimate_ClassificationData("H", "車載用金型・部品"));
            model.ClassificationDataList = ClassificationdataList;

            // 共通項目
            // 品種情報を取得
            var HinshudataList = new List<HinshuData>();
            HinshudataList.Add(new HinshuData("　", ""));
            HinshudataList.Add(new HinshuData("ZX-A001", "金型A図枠組み"));
            HinshudataList.Add(new HinshuData("ZX-B001", "金型B図枠組み"));
            HinshudataList.Add(new HinshuData("ZX-C001", "金型C図枠組み"));
            HinshudataList.Add(new HinshuData("ZX-D001", "金型D図枠組み"));
            HinshudataList.Add(new HinshuData("ZX-E001", "金型E図枠組み"));
            HinshudataList.Add(new HinshuData("ZX-F001", "金型F図枠組み"));
            HinshudataList.Add(new HinshuData("ZX-G001", "金型G図枠組み"));
            model.HinsyuDataList = HinshudataList;

            model.ClassificationSymbol = "A";
            return View(model);
        }

        public ActionResult EstimateReply(string partsClass, string partsName)
        {
            var model = new InquiryCostEstimateViewModel();
            var dataList = new List<EstimateReplyData>();
            dataList.Add(new EstimateReplyData("0000023452", "0000023534", "（株）阿部製作所", "8", "", "1", "", "概算", "型一式", "", "8", "280,000", "2,240,000", "2023/12/20", "2,300,000", "2023/12/21", "-60,000", true, 4, false));
            dataList.Add(new EstimateReplyData("0000023463", "0000023675", "（株）ゲートジャパン", "8", "", "1", "", "概算", "サンプル加工", "", "8", "295,000", "2,360,000", "2023/12/15", "2,300,000", "2023/12/21", "60,000", false, 0, false));
            dataList.Add(new EstimateReplyData("0000023464", "0000237874", "（株）メイホー", "8", "", "1", "非表示", "概算", "型一式", "辞退", "", "", "", "", "", "", "", false, 0, false));
            model.EstimateReplyDataList = dataList;

            model.selectPartsClass = partsClass;
            model.selectPartsName = partsName;

            return View(model);
        }

        [HttpPost]
        public ActionResult EstimateReplyAll()
        {
            JavaScriptSerializer sz = new JavaScriptSerializer();
            var dataList = new List<EstimateReplyData>();
            dataList.Add(new EstimateReplyData("0000023452", "0000023534", "（株）阿部製作所", "8", "", "1", "", "概算", "型一式", "", "8", "280,000", "2,240,000", "2023/12/20", "2,300,000", "2023/12/21", "-60,000", true, 4, false));
            dataList.Add(new EstimateReplyData("0000023463", "0000023675", "（株）ゲートジャパン", "8", "", "1", "", "概算", "サンプル加工", "", "8", "295,000", "2,360,000", "2023/12/15", "2,300,000", "2023/12/21", "60,000", false, 0, false));
            dataList.Add(new EstimateReplyData("0000023464", "0000237874", "（株）メイホー", "8", "", "1", "非表示", "概算", "型一式", "辞退", "", "", "", "", "", "", "", false, 0, false));
            string str = sz.Serialize(dataList);
            return Json(str);
        }


        [HttpPost]
        public ActionResult EstimateReplyDisplay()
        {
            JavaScriptSerializer sz = new JavaScriptSerializer();
            var dataList = new List<EstimateReplyData>();
            dataList.Add(new EstimateReplyData("0000023452", "0000023534", "（株）阿部製作所", "8", "", "1", "", "概算", "型一式", "", "8", "280,000", "2,240,000", "2023/12/20", "2,300,000", "2023/12/21", "-60,000", true, 4, false));
            dataList.Add(new EstimateReplyData("0000023463", "0000023675", "（株）ゲートジャパン", "8", "", "1", "", "概算", "サンプル加工", "", "8", "295,000", "2,360,000", "2023/12/15", "2,300,000", "2023/12/21", "60,000", false, 0, false));
            string str = sz.Serialize(dataList);
            return Json(str);
        }

        public ActionResult MailManager()
        {
            var model = new InquiryCostEstimateViewModel();
            var dataList = new List<MailManagerData>();
            dataList.Add(new MailManagerData("（株）阿部製作所", "採用", "test001@test.com", "", "採択結果", "採用となりました"));
            dataList.Add(new MailManagerData("（株）ゲートジャパン", "採用", "test001@test.com", "", "採択結果", "採用となりました"));
            dataList.Add(new MailManagerData("（株）メイホー", "不採用", "test001@test.com", "", "採択結果", "不採用となりました"));

            model.MailManagerDataList = dataList;

            return View(model);
        }

        public ActionResult MailSendHistory()
        {
            var model = new InquiryCostEstimateViewModel();
            var dataList = new List<MailSendHistoryData>();
            dataList.Add(new MailSendHistoryData("2023/07/01 12:20:01", "送信済", "パートナー工場", "1000100001", "（株）大阪製作所", "test001@test.com", "", "不採用メール", "採択結果", "不採用となりました"));
            dataList.Add(new MailSendHistoryData("2023/07/01 12:20:02", "送信済", "パートナー工場", "1000100002", "（株）京都製作所", "test001@test.com", "", "不採用メール", "採択結果", "不採用となりました"));
            dataList.Add(new MailSendHistoryData("2023/07/02 15:00:05", "送信済", "パートナー工場", "1000100003", "（株）兵庫工業", "test001@test.com", "", "不採用メール", "採択結果", "不採用となりました"));
            model.MailSendHistoryDataList = dataList;

            var dataList1 = new List<MailCategoryData>();
            dataList1.Add(new MailCategoryData("1", "　"));
            dataList1.Add(new MailCategoryData("2", "採用メール"));
            dataList1.Add(new MailCategoryData("", "不採用メール"));
            model.MailCategoryDataList = dataList1;

            model.SendDateFrom = DateTime.Now;
            model.SendDateTo = DateTime.Now;

            return View(model);
        }

        [HttpPost]
        public ActionResult FileUpload()
        {
            string fileName = "";
            foreach (string fName in Request.Files)
            {
                fileName = fName;
            }

            return Json(new { Message = fileName });
        }

        [HttpPost]
        public ActionResult FileDelete(string name)
        {
            return Json(new { Message = name });
        }

        [HttpPost]
        public JsonResult GetAssemblableReferenceData()
        {
            JavaScriptSerializer sz = new JavaScriptSerializer();
            var dataList = new List<AssemblableReferenceData>();
            dataList.Add(new AssemblableReferenceData());
            dataList.Add(new AssemblableReferenceData());
            dataList.Add(new AssemblableReferenceData());
            dataList.Add(new AssemblableReferenceData());
            dataList.Add(new AssemblableReferenceData());
            dataList.Add(new AssemblableReferenceData());
            dataList.Add(new AssemblableReferenceData());
            dataList.Add(new AssemblableReferenceData());
            dataList.Add(new AssemblableReferenceData());
            dataList.Add(new AssemblableReferenceData());

            string str = sz.Serialize(dataList);
            return Json(str);
        }

        [HttpPost]
        public JsonResult GetInquiryCostEstimateData()
        {
            JavaScriptSerializer sz = new JavaScriptSerializer();
            var dataList = new List<InquiryCostEstimateData>();
            dataList.Add(new InquiryCostEstimateData("1", "1", "A", "Upper Main Cavity", "001602-A-B001", true, "D", "2", "8", 300000, "3", "4", "1,120,000", "2023/12/20", "", " ", "〇"));
            dataList.Add(new InquiryCostEstimateData("2", "2", "B", "Upper Cull Block", "001602-A-B002", false, "A", "1", "2", 260000, "1", "0", "", "", "在庫品引当", " ", "〇"));
            dataList.Add(new InquiryCostEstimateData("3", "5", "D", "Upper Holder Vase", "001602-A-B003", false, "E", "1", "2", 150000, "1", "0", "", "", "", " ", "〇"));
            dataList.Add(new InquiryCostEstimateData("4", "8", "A", "Lower Main Cavity", "001602-A-B004_1", false, "B", "1", "2", 350000, "1", "0", "", "", "", " ", "〇"));
            dataList.Add(new InquiryCostEstimateData("5", "9", "A", "Lower Main Cavity", "001602-A-B004_2", false, "B", "1", "2", 350000, "1", "0", "", "", "", " ", "〇"));
            dataList.Add(new InquiryCostEstimateData("6", "12", "B", "Lower Port Block", "001602-A-B005", false, "A", "1", "2", 100000, "1", "0", "", "", "", " ", "〇"));

            string str = sz.Serialize(dataList);
            return Json(str);
        }

        [HttpPost]
        public JsonResult GetDrawingNumberData()
        {
            JavaScriptSerializer sz = new JavaScriptSerializer();
            var dataList = new List<DrawingNumberData>();
            dataList.Add(new DrawingNumberData());
            dataList.Add(new DrawingNumberData());
            dataList.Add(new DrawingNumberData());
            dataList.Add(new DrawingNumberData());
            dataList.Add(new DrawingNumberData());
            dataList.Add(new DrawingNumberData());
            dataList.Add(new DrawingNumberData());
            dataList.Add(new DrawingNumberData());
            dataList.Add(new DrawingNumberData());

CampusV4/Views/InquiryCostEstimate/AssemblableReference.cshtml
<style>
    #dlgAssemblableReference {
        width: 1088px;
    }
</style>

<div id="dlgAssemblableReference">
    <form id="frmAssemblableReference" class="form-horizontal">
        <h4 class="modal-header">
            組立可能数照会
            <button type="button" tabindex="-1" class="close wj-hide">&times;</button>
        </h4>
        <div class="modal-body">
            <div class="form-group">
                @(Html.C1().FlexGrid()
                    .AutoGenerateColumns(false).IsReadOnly(true).Height("308px").Id("grdAssemblableReference")
                    .Columns(b1 =>
                    {
                        b1.Add(cb => cb.Binding("Col_1").Width("80").Header("行"));
                        b1.Add(cb => cb.Binding("Col_2").Header("部品分類"));
                        b1.Add(cb => cb.Binding("Col_3").Width("220").Header("部品名"));
                        b1.Add(cb => cb.Binding("Col_6").Width("120").Header("入数"));
                        b1.Add(cb => cb.Binding("Col_7").Width("120").Header("個数"));
                        b1.Add(cb => cb.Binding("Col_8").Width("120").Header("数量"));
                        b1.Add(cb => cb.Binding("Col_9").Width("120").Header("仕入数"));
                        b1.Add(cb => cb.Binding("Col_10").Width("120").Header("可能数"));
                    }))
            </div>
            <div class="form-group">                
                <label class="col-md-offset-8 col-md-2 control-label" for="Text1">組立可能数</label>
                <div class="col-md-2">
                    <input class="form-control" id="Text1" name="Text1" type="text" disabled />
                </div>
            </div>
        </div>
        <div class="modal-footer">
            <button type="button" class="btn btn-default wj-hide">閉じる</button>
        </div>
    </form>
</div>

@Html.C1().Popup("#dlgAssemblableReference")

<script type="text/javascript">
    function loadAssemblableReferenceData() {
        $.ajax({
            type: "POST",
            url: "/InquiryCostEstimate/GetAssemblableReferenceData",
            dataType: "json",
            success: function (result) {
                var fg = wijmo.Control.getControl("#grdAssemblableReference");
                var data = JSON.parse(result);
                fg.rows.clear();
                var j = 0
                for (var i in data) {
                    var obj = [data[i].Col_1, data[i].Col_2, data[i].Col_3, data[i].Col_4, data[i].Col_5, data[i].Col_6, data[i].Col_7, data[i].Col_8, data[i].Col_9, data[i].Col_10];
                    // FlexGridに新規行を追加します。
                    var row = new wijmo.grid.Row();
                    fg.rows.push(row);
                    for (var col = 0; col <= fg.columns.length - 1; col++) {
                        //FlexGrid のセルにデータを入力します。
                        fg.setCellData(j, col, obj[col]);
                    }
                    j++;
                }
            }
        });
    }
</script>

CampusV4/Views/InquiryCostEstimate/EstimateReference.cshtml
<style>
    #dlgEstimateReference {
        width: 500px;
    }
</style>

<div id="dlgEstimateReference">
    <form id="frmEstimateReference" class="form-horizontal">
        <h4 class="modal-header">
            概算見積参照
            <button type="button" tabindex="-1" class="close wj-hide">&times;</button>
        </h4>
        <div class="modal-body">
            <div class="form-group">
                @(Html.C1().FlexGrid()
                    .AutoGenerateColumns(false).IsReadOnly(true).Height("308px").Id("grdEstimateReference")
                    .Columns(b1 =>
                    {
                        b1.Add(cb => cb.Binding("Col_1").Width("150").Header("単価").Align("right"));
                        b1.Add(cb => cb.Binding("Col_2").Width("150").Header("納期").Align("center"));
                    }))
            </div>
        </div>
        <div class="modal-footer">
            <button type="button" class="btn btn-default wj-hide">閉じる</button>
        </div>
    </form>
</div>

@Html.C1().Popup("#dlgEstimateReference")

<script type="text/javascript">
    function loadEstimateReferenceData() {
        $.ajax({
            type: "POST",
            url: "/InquiryCostEstimate/GetEstimateReferenceData",
            dataType: "json",
            success: function (result) {
                var fg = wijmo.Control.getControl("#grdEstimateReference");
                var data = JSON.parse(result);
                fg.rows.clear();
                var j = 0
                for (var i in data) {
                    var obj = [data[i].Col_1, data[i].Col_2];
                    // FlexGridに新規行を追加します。
                    var row = new wijmo.grid.Row();
                    fg.rows.push(row);
                    for (var col = 0; col <= fg.columns.length - 1; col++) {
                        //FlexGrid のセルにデータを入力します。
                        fg.setCellData(j, col, obj[col]);
                    }
                    j++;
                }
            }
        });
    }
</script>

CampusV4/Views/InquiryCostEstimate/EstimateReply.cshtml
@model CampusV4.Models.InquiryCostEstimateViewModel

<style>
    .breadcrumb {
        font-size: 24px;
    }
</style>

<div id="EstimateReply">
    <div style="transform-origin: left top;">
        <div class="page-title">
            <div class="title_left">
                <ol class="breadcrumb">
                    <li><a href="/InquiryCostEstimate/Index">引合別原価見積一覧 <i class="fa fa-arrow-circle-left"></i></a></li>
                    <li class="active">見積回答</li>
                </ol>
            </div>
        </div>
        <div class="clearfix"></div>
        <div class="row">
            <div class="col-md-12">
                <div class="x_panel">
                    @using (Html.BeginForm("Regist", "InquiryCostEstimate", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
                    {
                        @Html.AntiForgeryToken()

                        <div class="form-group">
                            <label class="col-md-1 control-label" for="Text1">部品分類</label>
                            <div class="col-md-2">
                                <input class="form-control" id="Text1" name="Text1" type="text" disabled value="A" />
                            </div>
                            <label class="col-md-1 control-label" for="Text2">部品名</label>
                            <div class="col-md-6">
                                <input class="form-control" id="Text2" name="Text2" type="text" disabled value="Upper Main Cavity" />
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-md-1 control-label" for="Text3">数量</label>
                            <div class="col-md-2">
                                <input class="form-control" id="Text3" name="Text3" type="text" value="8" disabled />
                            </div>
                            <label class="col-md-1 control-label" for="Text4">納入希望日</label>
                            <div class="col-md-4">
                                <input class="form-control" id="Text4" name="Text4" type="text" value="2023/12/28" disabled />
                            </div>
                        </div>
                        @*<div class="input-group">
                            <div class="input-group-addon"><span class="glyphicon glyphicon-search"></span></div>
                            <input id="filter" class="form-control">
                        </div>*@
                        <div class="form-group">
                            @(Html.C1().FlexGrid()
                            .AutoGenerateColumns(false).Height("495px").Id("grdEstimateReply").DefaultRowSize(45).FrozenColumns(5)
                            .Bind(b => b.Bind(Model.EstimateReplyDataList).DisableServerRead(true))
                            .Columns(b1 =>
                            {
                                b1.Add(cb => cb.Binding("Col_1").Width("120").Header("原価見積依頼番号").IsReadOnly(true));
                                b1.Add(cb => cb.Binding("Col_2").Width("120").Header("見積回答番号").IsReadOnly(true));
                                b1.Add(cb => cb.Binding("Col_3").Width("250").Header("パートナー工場").IsReadOnly(true));
                                b1.Add(cb => cb.Binding("Col_4").Width("60").Header("数量").IsReadOnly(true).Align("center"));
                                b1.Add(cb => cb.Binding("Col_5").Width("70").Header("再").IsReadOnly(true).Align("center"));
                                b1.Add(cb => cb.Binding("Col_7").Width("120").Header("表示選択").IsReadOnly(true).Align("center"));
                                b1.Add(cb => cb.Binding("Col_8").Width("120").Header("見積依頼区分").IsReadOnly(true).Align("center"));
                                b1.Add(cb => cb.Binding("Col_8_1").Width("120").Header("加工区分依頼").IsReadOnly(true).Align("center"));
                                b1.Add(cb => cb.Binding("Col_9").Width("120").Header("辞退区分").IsReadOnly(true).Align("center"));
                                b1.Add(cb => cb.Binding("Col_10").Width("80").Header("数量").IsReadOnly(true).Align("center"));
                                b1.Add(cb => cb.Binding("Col_11").Width("100").Header("単価").IsReadOnly(true).DataType(DataType.Number));
                                b1.Add(cb => cb.Binding("Col_12").Width("100").Header("金額").IsReadOnly(true).DataType(DataType.Number));
                                b1.Add(cb => cb.Binding("Col_13").Width("100").Header("納期").IsReadOnly(true));
                                b1.Add(cb => cb.Binding("Col_13_1").Width("100").Header("概算金額").IsReadOnly(true).DataType(DataType.Number));
                                b1.Add(cb => cb.Binding("Col_13_2").Width("100").Header("概算納期").IsReadOnly(true).DataType(DataType.Number));
                                b1.Add(cb => cb.Binding("Col_13_3").Width("100").Header("差額").IsReadOnly(true).DataType(DataType.Number));
                                b1.Add(cb => cb.Binding("Col_14").Width("120").Header("採用").DataType(DataType.Boolean));
                                b1.Add(cb => cb.Binding("Col_15").Width("120").Header("採用数").DataType(DataType.Number));
                                b1.Add(cb => cb.Binding("Col_16").Width("120").Header("不採用").DataType(DataType.Boolean));
                            }))
                        </div>
                        <div class="form-group">
                            <label class="col-md-offset-4 col-md-2 control-label" for="Text5">合計数量</label>
                            <div class="col-md-2">
                                <input class="form-control" id="Text5" name="Text5" type="text" disabled />
                            </div>
                            <label class="col-md-2 control-label" for="Text6">合計金額</label>
                            <div class="col-md-2">
                                <input class="form-control" id="Text6" name="Text6" type="text" disabled />
                            </div>
                        </div>

                        <div class="ln_solid"></div>
                        <div class="form-group">
                            <div class="col-md-8 col-md-offset-4" style="text-align: right">
                                <input type="button" class="btn btn-primary" id="replyAll" onclick="loadEstimateReplyAllData();" value="全明細表示">
                                <input type="button" class="btn btn-primary" id="reply" onclick="loadEstimateReplyData();" value="標準明細表示">
                                <a href="/InquiryCostEstimate/MailManager" class="btn btn-primary">メール送信</a>
                                <input type="submit" class="btn btn-primary" value="登録">
                            </div>
                        </div>
                    }
                </div>
            </div>
        </div>
    </div>
</div>

@Html.Partial("ReasonChoice")
@Html.Partial("EstimateSecurity")

<script type="text/javascript">
    c1.documentReady(function () {
        document.getElementById("replyAll").style.display = "inline";
        document.getElementById("reply").style.display = "none";
        var gridEstimateReply = wijmo.Control.getControl('#grdEstimateReply');
        var dlgReasonChoice = wijmo.Control.getControl('#dlgReasonChoice');
        var dlgEstimateSecurity = wijmo.Control.getControl('#dlgEstimateSecurity');
        /*var dlgMailManager = wijmo.Control.getControl('#dlgMailManager');*/

        //document.getElementById('filter').addEventListener('input', function (e) {
        //    var filter = e.target.value.toLowerCase();
        //    gridEstimateReply.collectionView.filter = function (item) {
        //        return filter.length == 0 || item.Col_1.toLowerCase().indexOf(filter) > -1
        //    }
        //});

        gridEstimateReply.formatItem.addHandler(function (s, e) {
            if (e.panel == s.cells) {
                if (s.columns[e.col].binding == 'Col_5') {
                    var item = gridEstimateReply.cells.getCellData(e.row, e.col, false);
                    e.cell.innerHTML = '<a class="btn btn-info" name="estimate_input"><i class="fa fa-pencil-square"></i></a>';
                } else if (s.columns[e.col].binding == 'Col_15') {
                    var item = gridEstimateReply.cells.getCellData(e.row, e.col, false);
                    e.cell.innerHTML = '<div class="input-group"><input class="form-control" disabled value="' + item + '"><span class="input-group-btn"><a class="btn btn-info" name="estimate_security"><i class="fa fa-search"></i></a></span>';
                }
            }
        });

        gridEstimateReply.hostElement.addEventListener('mousedown', function (e) {
            if (e.target.type === "checkbox") {
                dlgReasonChoice.show(true, function (sender) {
                    switch (sender.dialogResult) {
                        case 'submit':
                            alert('form submitted');
                            break;
                        case 'wj-hide-create':
                            break;
                    }
                });
            }
        });

        gridEstimateReply.hostElement.addEventListener('click', function (e) {
            var target = wijmo.closest(e.target, 'a');
            if (target instanceof HTMLAnchorElement) {
                if (target.name == 'estimate_security') {
                    loadEstimateSecurityData();
                    dlgEstimateSecurity.show(true, function (sender) {
                        switch (sender.dialogResult) {
                            case 'submit':
                                alert('form submitted');
                                break;
                            case 'wj-hide-create':
                                break;
                        }
                    });
                }
            }
        });

        loadEstimateReplyData();

        //document.getElementById('btnMailManager').addEventListener('click', function () {
        //    loadMailManagerData();
        //    dlgMailManager.show(true, function (sender) {
        //        switch (sender.dialogResult) {
        //            case 'submit':
        //                alert('form submitted');
        //                break;
        //            case 'wj-hide-create':
        //                break;
        //        }
        //    });
        //});
    });

   
    function loadEstimateReplyAllData() {
        document.getElementById("replyAll").style.display = "none";
        document.getElementById("reply").style.display = "inline";
        var theGrid = wijmo.Control.getControl("#grdEstimateReply");
        var filter = '';
        theGrid.collectionView.filter = function (item) {
            return filter.length == 0 || item.Col_7.toLowerCase().indexOf(filter) > -1
        }
        //$.ajax({
        //    type: "POST",
        //    url: "/InquiryCostEstimate/EstimateReplyAll",
        //    dataType: "json",
        //    success: function (result) {
        //        var fg = wijmo.Control.getControl("#grdEstimateReply");
        //        var data = JSON.parse(result);
        //        fg.rows.clear();
        //        var j = 0
        //        for (var i in data) {
        //            var obj = [data[i].Col_1, data[i].Col_2, data[i].Col_3, data[i].Col_4, data[i].Col_5,
        //            data[i].Col_6, data[i].Col_7, data[i].Col_8, data[i].Col_9, data[i].Col_10,
        //            data[i].Col_11, data[i].Col_12, data[i].Col_13, data[i].Col_14, data[i].Col_15, data[i].Col_16];
        //            // FlexGridに新規行を追加します。
        //            var row = new wijmo.grid.Row();
        //            fg.rows.push(row);
        //            for (var col = 0; col <= fg.columns.length - 1; col++) {
        //                //FlexGrid のセルにデータを入力します。
        //                fg.setCellData(j, col, obj[col]);
        //            }
        //            j++;
        //        }
        //    }
        //});
    }
    function loadEstimateReplyData() {
        document.getElementById("replyAll").style.display = "inline";
        document.getElementById("reply").style.display = "none";
        var theGrid = wijmo.Control.getControl("#grdEstimateReply");
        var filter = '8';
        theGrid.collectionView.filter = function (item) {
            return filter.length == 0 || item.Col_10.toLowerCase().indexOf(filter) > -1
        }
        //$.ajax({
        //    type: "POST",
        //    url: "/InquiryCostEstimate/EstimateReplyDisplay",
        //    dataType: "json",
        //    success: function (result) {
        //        var fg = wijmo.Control.getControl("#grdEstimateReply");
        //        var data = JSON.parse(result);
        //        fg.rows.clear();
        //        var j = 0
        //        for (var i in data) {
        //            var obj = [data[i].Col_1, data[i].Col_2, data[i].Col_3, data[i].Col_4, data[i].Col_5,
        //            data[i].Col_6, data[i].Col_7, data[i].Col_8, data[i].Col_9, data[i].Col_10,
        //            data[i].Col_11, data[i].Col_12, data[i].Col_13, data[i].Col_14, data[i].Col_15, data[i].Col_16];
        //            // FlexGridに新規行を追加します。
        //            var row = new wijmo.grid.Row();
        //            fg.rows.push(row);
        //            for (var col = 0; col <= fg.columns.length - 1; col++) {
        //                //FlexGrid のセルにデータを入力します。
        //                fg.setCellData(j, col, obj[col]);
        //            }
        //            j++;
        //        }
        //    }
        //});
    }
</script>

CampusV4/Views/InquiryCostEstimate/ReasonChoice.cshtml
<style>
    #dlgReasonChoice {
        width: 600px;
    }
</style>

<div id="dlgReasonChoice">
    <form id="frmReasonChoice" class="form-horizontal">
        <h4 class="modal-header">
            理由選択
            <button type="button" tabindex="-1" class="close wj-hide">&times;</button>
        </h4>
        <div class="modal-body">
            <p>理由を選択してください。</p>
            <div class="form-group">
                <div class="col-md-2">
                    <select class="form-control" id="Select1" name="Select1">
                    </select>
                </div>
                <div class="col-md-8">
                    <input class="form-control" id="Text1" name="Text1" type="text" />
                </div>
            </div>
        </div>
        <div class="modal-footer">
            <button type="button" class="btn btn-default wj-hide">閉じる</button>
        </div>
    </form>
</div>

@Html.C1().Popup("#dlgReasonChoice")