CampusV4/Models/M_EmployeeViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace CampusV4.Models
{
    public class M_EmployeeViewModel
    {
        public string Mode { get; set; }

        //担当者コード
        public string UserId { get; set; }
        //担当者名
        public string UserName { get; set; }
        //担当者名（外国語）
        public string UserNameAlt { get; set; }
        //所属部門コード
        public string DepartmentCode { get; set; }
        //所属部門名
        public string DepartmentName { get; set; }
        //E-mail
        public string Email { get; set; }
        //パスワード
        public string Password { get; set; }
        //メニューID
        public string MenuId { get; set; }
        //メニュー名
        public string MenuName { get; set; }
        //パスワード変更日
        public DateTime? PasswordChangeDate { get; set; }
        //在職区分
        public string IsRetired { get; set; }
        //上長担当者コード
        public string SupervisorPicCode { get; set; }
        //上長担当者名
        public string SupervisorPicName { get; set; }
        //承認者区分
        public string IsApproverStr { get; set; }
        //承認者区分フラグ（承認者区分=1の場合、Ture）
        public bool IsApprover { get; set; }
        //削除フラグ
        public bool DeleteFlg { get; set; }

        //URL
        public string URL { get; set; }

        //作成日
        public DateTime? CreatedAt { get; set; }
        //作成者コード
        public string CreatedBy { get; set; }
        //作成者名
        public string CreatedName { get; set; }
        //作成プログラムID
        public string CreatedPid { get; set; }
        //更新日
        public DateTime? UpdatedAt { get; set; }
        //更新者コード
        public string UpdatedBy { get; set; }
        //更新者名
        public string UpdatedName { get; set; }
        //更新プログラムID
        public string UpdatedPid { get; set; }
        //削除日
        public DateTime? DeletedAt { get; set; }
        //削除者コード
        public string DeletedBy { get; set; }
        //削除者名
        public string DeletedName { get; set; }
        //削除プログラムID
        public string DeletedPid { get; set; }

        
        //所属部門リスト
        public List<MasterData> DepartmentList { get; set; }

        //上長担当者リスト
        public List<EmployeeData> EmployeeList { get; set; }

        //メニューリスト
        public List<MasterData> MenuList { get; set; }
    }


    public class M_EmployeeSearchViewModel
    {

        //担当者コード
        public string UserId { get; set; }
        //担当者名
        public string UserName { get; set; }

        public List<M_EmployeeViewModel> EmployeeDataList { get; set; }

    }
}

CampusV4/Controllers/M_EmployeeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using C1.Web.Mvc;
using C1.Web.Mvc.Serialization;
using System.Web;
using System.Data;
using System.Web.Mvc;
using System.Data.Entity;
using CampusV4.Models;

// This code was generated by C1 Scaffolder.

namespace CampusV4.Controllers.M_Employee
{
    public partial class M_EmployeeController : Controller
    {
        public ActionResult Index()
        {
            M_EmployeeSearchViewModel model = new M_EmployeeSearchViewModel();
            return View("EmployeeSearch",model);
        }

        //担当者マスタ一覧検索
        public ActionResult EmployeeSearch(M_EmployeeSearchViewModel model)
        {
            GetEmployeeListSearch(ref model);
            return View(model);
        }

        //担当者マスタ一覧削除
        public ActionResult EmployeeListDelete(M_EmployeeSearchViewModel model)
        {
            GetEmployeeListSearch(ref model);
            return View("EmployeeSearch", model);
        }
        //担当者マスタ詳細画面へ遷移
        public ActionResult EmployeeDetail(string UserId)
        {
            M_EmployeeViewModel model = new M_EmployeeViewModel();
            GetInitDataList(ref model);
            if (UserId == "")
            {
                model.Mode = "ins";
                model.IsRetired = "1";
            }
            else
            {
                model.Mode = "upd";
                GetEmployeeData(ref model);
            }

            return View(model);
        }

        //リストボックス値取得
        private void GetInitDataList(ref M_EmployeeViewModel model)
        {

            // 上長担当者情報を取得
            var TantoshaData = new List<EmployeeData>();
            TantoshaData.Add(new EmployeeData("　", ""));
            TantoshaData.Add(new EmployeeData("USR00001", "佐藤　一郎"));
            TantoshaData.Add(new EmployeeData("USR00002", "佐藤　次郎"));
            TantoshaData.Add(new EmployeeData("USR00003", "佐藤　三郎"));
            TantoshaData.Add(new EmployeeData("USR00004", "佐藤　四朗"));
            TantoshaData.Add(new EmployeeData("USR00005", "佐藤　五郎"));
            model.EmployeeList = TantoshaData;

            // 所属部門を取得
            var DepartmentList = new List<MasterData>();
            DepartmentList.Add(new MasterData("　", ""));
            DepartmentList.Add(new MasterData("001", "営業部"));
            DepartmentList.Add(new MasterData("002", "調達部"));
            model.DepartmentList = DepartmentList;

            // メニューを取得
            var MenuList = new List<MasterData>();
            MenuList.Add(new MasterData("　", ""));
            MenuList.Add(new MasterData("001", "メニュー１"));
            MenuList.Add(new MasterData("002", "メニュー２"));
            model.MenuList = MenuList;



        }

        private void GetEmployeeListSearch(ref M_EmployeeSearchViewModel model)
        {
            List<M_EmployeeViewModel> EmployeeDataList = new List<M_EmployeeViewModel>();
            M_EmployeeViewModel employeeData = new M_EmployeeViewModel();
            employeeData.UserId = "USR00001";
            employeeData.UserName = "佐藤　一郎";
            employeeData.UserNameAlt = "ICHIRO SATO";
            employeeData.DepartmentCode = "001";
            employeeData.DepartmentName = "営業部";
            employeeData.Email = "SATO1xxxx@xxx.com";
            employeeData.URL = "/M_Employee/EmployeeDetail?UserId="+ employeeData.UserId;
            EmployeeDataList.Add(employeeData);

            M_EmployeeViewModel employeeData1 = new M_EmployeeViewModel();
            employeeData1.UserId = "USR00002";
            employeeData1.UserName = "佐藤　二郎";
            employeeData1.UserNameAlt = "JIRO SATO";
            employeeData1.DepartmentCode = "001";
            employeeData1.DepartmentName = "営業部";
            employeeData1.Email = "SATO2xxxx@xxx.com";
            employeeData1.URL = "/M_Employee/EmployeeDetail?UserId=" + employeeData1.UserId;
            EmployeeDataList.Add(employeeData1);

            M_EmployeeViewModel employeeData2 = new M_EmployeeViewModel();
            employeeData2.UserId = "USR00003";
            employeeData2.UserName = "佐藤　三郎";
            employeeData2.UserNameAlt = "SABURO SATO";
            employeeData2.DepartmentCode = "002";
            employeeData2.DepartmentName = "調達部";
            employeeData2.Email = "SATO3xxxx@xxx.com";
            employeeData2.URL = "/M_Employee/EmployeeDetail?UserId=" + employeeData2.UserId;

            EmployeeDataList.Add(employeeData2);

            model.EmployeeDataList = EmployeeDataList;


        }

        private void GetEmployeeData(ref M_EmployeeViewModel model)
        {

            model.UserId = "USR00001";
            model.UserName = "佐藤　一郎";
            model.UserNameAlt = "ICHIRO SATO";
            model.DepartmentCode = "001";
            model.DepartmentName = "営業部";
            model.Email = "SATO1xxxx@xxx.com";

            model.Password = "abc123";
            model.MenuId = "001";
            model.MenuName = "メニュー１";
            model.PasswordChangeDate = DateTime.Parse("2023/01/30");
            model.IsRetired = "1";
            model.SupervisorPicCode = "USR00003";
            model.SupervisorPicName = "佐藤　三郎";
            model.IsApproverStr = "1";
            model.IsApprover = true;

            model.CreatedAt = DateTime.Parse("2023/01/01");
            model.CreatedBy = "USR00002";
            model.CreatedName = "佐藤　二郎";
            model.CreatedPid = "PID0001";
            model.UpdatedAt = DateTime.Parse("2023/01/30"); ;
            model.UpdatedBy = "USR00002";
            model.UpdatedName = "佐藤　二郎";
            model.UpdatedPid = "PID0001";
            model.DeletedAt = null;
            model.DeletedBy = "";
            model.DeletedName = "";
            model.DeletedPid = "";
    }
        }
}

CampusV4/Views/M_Employee/EmployeeSearch.cshtml
@model CampusV4.Models.M_EmployeeSearchViewModel

<div>
    <div class="page-title">
        <div class="title_left">
            <h3>担当者マスタ一覧</h3>
        </div>
    </div>
    <div class="clearfix"></div>
    <div class="row">
        <div class="col-md-12">
            <div class="x_panel">
                @using (Html.BeginForm("EmployeeSearch", "M_Employee", FormMethod.Post, new { @class = "form-horizontal", role = "form", defaultbutton = "dummySubmit" }))
                {
                    @Html.AntiForgeryToken()

                    <div class="form-group">
                        <label class="col-md-1 control-label text-nowrap" id="lbl_UserId" for="UserId">担当者コード</label>
                        <div class="col-md-2">
                            @Html.TextBoxFor(model => model.UserId, new { @class = "form-control", @id = "UserId" })
                        </div>
                        <label class="col-md-1 control-label text-nowrap" id="lbl_UserName" for="UserName">担当者名</label>
                        <div class="col-md-2">
                            @Html.TextBoxFor(model => model.UserName, new { @class = "form-control", @id = "UserName" })
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-md-12" style="text-align: right">
                            <input type="submit" id="dummySubmit" value="Dummy" class="btn btn-primary" name="submitBtn" style="display:none;" onclick="return false;" />
                            <input type="submit" value="新規登録" name="btnRegist" class="btn btn-primary" formaction="/M_Employee/EmployeeDetail?UserId=" id="btnRegist" />
                            <input type="submit" value="検索" name="ShowSearchBtn" class="btn btn-primary" id="ShowSearchBtn"/>
                        </div>
                    </div>

                    <div class="form-group">
                        @(Html.C1().FlexGrid()
                            .AutoGenerateColumns(false).Height("450px").Id("flexgrid").AllowAddNew(false)
                            .Bind(Model.EmployeeDataList)
                            .Columns(b1 =>
                            {
                                b1.Add(cb => cb.Binding("UserId").Width("150").Header("担当者コード").WordWrap(true).IsReadOnly(true));
                                b1.Add(cb => cb.Binding("UserName").Width("200").Header("担当者名").WordWrap(true).IsReadOnly(true));
                                b1.Add(cb => cb.Binding("UserNameAlt").Width("200").Header("担当者名（外国語）").WordWrap(true).IsReadOnly(true));
                                b1.Add(cb => cb.Binding("DepartmentCode").Width("150").Header("所属部門コード").WordWrap(true).IsReadOnly(true));
                                b1.Add(cb => cb.Binding("DepartmentName").Width("200").Header("所属部門名").WordWrap(true).IsReadOnly(true));
                                b1.Add(cb => cb.Binding("Email").Width("200").Header("E-mail").WordWrap(true).IsReadOnly(true));
                                b1.Add(cb => cb.Binding("DeleteFlg").Width("50").Header("削除").WordWrap(true));

                            }))
                    </div>

                    <div class="ln_solid"></div>
                    <div class="form-group">
                        <div class="col-md-12" style="text-align: right">
                            <input type="submit" value="削除" name="btnClose" class="btn btn-primary" formaction="/M_Employee/EmployeeListDelete" id="btnClose" />
                        </div>
                    </div>
                }
            </div>
        </div>
    </div>
</div>


@section scripts{
    <script>

        // ラベルツールチップ設定
        var tt = new wijmo.Tooltip();
        tt.setTooltip('#lbl_UserId', '担当者コード');
        tt.setTooltip('#lbl_UserName', '担当者名');



        //Gridダブルクリックイベント
        var grid = wijmo.Control.getControl('#flexgrid');
        grid.hostElement.addEventListener('dblclick', function (e) {
            var ht = grid.hitTest(e.pageX, e.pageY);

            if (ht.cellType == wijmo.grid.CellType.Cell) {
                var sel = grid.selection;
                var Url = "";
                for (var r = sel.topRow; r <= sel.bottomRow; r++) {
                    var Url = grid.rows[r].dataItem.URL;
                }
                window.location.href = Url;
            }

        });

    </script>
}