CampusV4/Controllers/SampleController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using CampusV4.Models;

namespace CampusV4.Controllers
{
    public class SampleController : Controller
    {
        // GET: Sample
        public ActionResult Index()
        {
            var model = new Sample1ViewModel();
            var dataList = new List<IndexGridData>();
            dataList.Add(new IndexGridData("1", "A", "Upper Main Cavity A", "1","2","10","2023/01/01", "2023/01/02"));
            dataList.Add(new IndexGridData("2", "B", "Upper Cull Block B", "3", "4", "20", "2023/02/01", "2023/02/02"));
            dataList.Add(new IndexGridData("3", "C", "Upper Main Cavity C", "5", "6", "30", "2023/03/01", "2023/03/02"));
            dataList.Add(new IndexGridData("4", "D", "Upper Cull Block D", "1", "2", "40", "2023/04/01", "2023/04/02"));
            dataList.Add(new IndexGridData("5", "A", "Upper Main Cavity A", "3", "4", "50", "2023/05/01", "2023/05/02"));
            dataList.Add(new IndexGridData("6", "B", "Upper Cull Block B", "5", "6", "60", "2023/06/01", "2023/06/02"));
            dataList.Add(new IndexGridData("7", "C", "Upper Main Cavity C", "1", "2", "70", "2023/07/01", "2023/07/02"));
            dataList.Add(new IndexGridData("8", "D", "Upper Cull Block D", "3", "4", "80", "2023/08/01", "2023/08/02"));

            model.IndexDataList = dataList;

            var subDataList = new List<DialogGridData>();
            subDataList.Add(new DialogGridData());
            subDataList.Add(new DialogGridData());
            subDataList.Add(new DialogGridData());
            subDataList.Add(new DialogGridData());
            subDataList.Add(new DialogGridData());
            subDataList.Add(new DialogGridData());
            subDataList.Add(new DialogGridData());
            subDataList.Add(new DialogGridData());

            model.DialogDataList = subDataList;

            return View(model);
        }

        public ActionResult Login()
        {
            return View();
        }

        public ActionResult Input1()
        {
            return View();
        }

        public ActionResult InquiryRegister()
        {
            return View();
        }

        public ActionResult Input2()
        {
            var model = new Sample1ViewModel();
            var dataList = new List<SeibanData>();
            dataList.Add(new SeibanData("1"));
            dataList.Add(new SeibanData("2"));
            dataList.Add(new SeibanData("3"));
            dataList.Add(new SeibanData("4"));
            dataList.Add(new SeibanData("5"));
            dataList.Add(new SeibanData("6"));
            dataList.Add(new SeibanData("7"));
            dataList.Add(new SeibanData("8"));
            dataList.Add(new SeibanData("9"));
            dataList.Add(new SeibanData("10"));

            model.GridDataList = dataList;
            return View(model);
        }

        public ActionResult Input3()
        {
            var model = new Sample2ViewModel();
            var dataList = new List<MitsumoriData>();
            dataList.Add(new MitsumoriData("001"));
            dataList.Add(new MitsumoriData("002"));
            dataList.Add(new MitsumoriData("003"));
            dataList.Add(new MitsumoriData("004"));
            dataList.Add(new MitsumoriData("005"));
            dataList.Add(new MitsumoriData("006"));
            dataList.Add(new MitsumoriData("007"));
            dataList.Add(new MitsumoriData("008"));
            dataList.Add(new MitsumoriData("009"));
            dataList.Add(new MitsumoriData("010"));

            model.GridDataList = dataList;
            return View(model);
        }

    }
}

CampusV4/Views/Sample/Input1.cshtml
<div>
    <div class="page-title">
        <div class="title_left">
            <h3>引合登録</h3>
        </div>
    </div>
    <div class="clearfix"></div>
    <div class="row">
        <div class="col-md-12">
            <div class="x_panel">
                @using (Html.BeginForm("Input1", "Sample", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
                {
                    @Html.AntiForgeryToken()
                    <p style="font-weight:bold;">登録しました（メッセージ枠）</p>
                    <p style="font-weight:bold;"><u>[受注入力]</u></p>
                    <div class="form-group">
                        <label class="col-md-1 control-label" for="Text1">受注番号</label>
                        <div class="col-md-2">
                            <div class="input-group">
                                <input class="form-control" id="Text1" name="Text1" type="text" />
                                <span class="input-group-btn">
                                    <button type="button" class="btn btn-info" id="btnSearchJuchu"><i class="fa fa-search"></i></button>
                                </span>
                            </div>
                        </div>
                        <label class="col-md-1 control-label" for="Text2">引合番号</label>
                        <div class="col-md-2">
                            <input class="form-control" id="Text2" name="Text2" type="text" />
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-md-1 control-label" for="Text3">受注日</label>
                        <div class="col-md-3">
                            @Html.C1().InputDate().Id("Text3")
                        </div>
                        <label class="col-md-2 control-label" for="Text4">不具合製番</label>
                        <div class="col-md-4">
                            <input class="form-control" id="Text4" name="Text4" type="text" />
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-md-1 control-label" for="Text5">稟議番号</label>
                        <div class="col-md-2">
                            <input class="form-control" id="Text5" name="Text5" type="text" />
                        </div>
                        <label class="col-md-1 control-label" for="Text6">納期</label>
                        <div class="col-md-3">
                            @Html.C1().InputDate().Id("Text6")
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-md-1 control-label" for="Select1">分類記号</label>
                        <div class="col-md-1">
                            <select class="form-control" id="Select1" name="Select1">
                            </select>
                        </div>
                        <label class="col-md-1 control-label" for="Text6">纏め製番</label>
                        <div class="col-md-4">
                            <input class="form-control" id="Text6" name="Text6" type="text" />
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-md-1 control-label" for="Text7">注文番号</label>
                        <div class="col-md-4">
                            <input class="form-control" id="Text7" name="Text7" type="text" />
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-md-2 control-label" for="Select2">営業担当者</label>
                        <div class="col-md-2">
                            <select class="form-control" id="Select2" name="Select2">
                            </select>
                        </div>
                        <div class="col-md-4">
                            <input class="form-control" id="Text8" name="Text8" type="text" />
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-md-2 control-label" for="Select3">調達担当者</label>
                        <div class="col-md-2">
                            <select class="form-control" id="Select3" name="Select3">
                            </select>
                        </div>
                        <div class="col-md-4">
                            <input class="form-control" id="Text9" name="Text9" type="text" />
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-md-offset-2 col-md-2">
                            <div class="checkbox">
                                <label>
                                    <input type="checkbox" value="test" />内示
                                </label>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <label class="control-label">先行手配（</label>
                            <label>
                                <input type="radio" name="Radio1" value="test" /> 有り
                            </label>
                            <label>
                                <input type="radio" name="Radio1" value="test" /> 無し
                            </label>
                            <label class="control-label">）</label>
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-md-offset-2 col-md-2">
                            <div class="checkbox">
                                <label>
                                    <input type="checkbox" value="test" />キャンセル
                                </label>
                            </div>
                        </div>
                        <div class="col-md-3">
                            @Html.C1().InputDate().Id("Text10")
                        </div>
                    </div>
                    <div class="form-group">

                    </div>
                    <div class="form-group">

                    </div>
                    <div class="form-group">

                    </div>
                    <div class="ln_solid"></div>
                    <div class="item form-group">
                        <div class="col-md-6 col-sm-6 col-md-offset-3">
                            <a href="@Url.Action("Input2")" class="btn btn-primary">製番明細</a>
                            <a href="#" class="btn btn-primary">検収明細</a>
                            <a href="#" class="btn btn-primary">登録</a>
                        </div>
                    </div>
                }
            </div>
        </div>
    </div>
</div>

@Html.Partial("../Common/MasterSearch")

@section scripts{
    <script>
        var dlgMasterSearch= wijmo.Control.getControl('#dlgMasterSearch');
        c1.documentReady(function () {
            document.getElementById('btnSearchJuchu').addEventListener('click', function () {
                loadMasterData();

                dlgMasterSearch.show(true, function (sender) {
                    if (sender.dialogResult == 'wj-hide-ok') {
                        document.getElementById('Text1').setAttribute('value', masterSelected.name);
                    }
                });
            });
            document.getElementById('Text1').addEventListener('keydown', function (e) {
                if (e.ctrlKey && e.keyCode == 113) {
                    let target = document.getElementById('btnSearchJuchu');
                    let clickEvent = new Event('click', { "bubbles": true, "cancelable": true });
                    target.dispatchEvent(clickEvent);
                }
            });
        });
    </script>
}

CampusV4/Views/Sample/Input2.cshtml
<div>
    <div class="page-title">
        <div class="title_left">
            <h3>テスト用呼出し</h3>
        </div>
    </div>
    <div class="clearfix"></div>
    <div class="row">
        <div class="col-md-12">
            <div class="x_panel">
                <div class="item form-group">
                    <div class="col-md-offset-5 col-md-2">
                        <button type="button" class="btn btn-info" id="btnMailManager">メール送信</button>
                        <button class="btn btn-primary wj-hide-ok">選択</button>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<a href="#" class="btn btn-primary" id="btnInsert">登録</a>
<!-- モーダル・ダイアログ -->
<div id="dialog" style="width: 600px; height: 200px;">
    <div class="wj-dialog-header">
        @Html.Raw("メッセージ")
    </div>
    <div class="wj-dialog-body">
        <p>
            @Html.Raw("登録が完了しました")
        </p>
    </div>
    <div class="wj-dialog-footer">
        <button class="btn btn-default wj-hide-ok">OK</button>
    </div>
</div>
@Html.C1().Popup("#dialog")

@Html.Partial("../Common/MailManager")
@*@Html.C1().Popup("#exampleModalToggle")
    @Html.C1().Popup("#exampleModalToggle2")*@

@section scripts{
    <script>
        var dlgMailManager = wijmo.Control.getControl('#dlgMailManager');
        // show forms
        document.getElementById('btnMailManager').addEventListener('click', function () {
            dlgMailManager.show(true, function (sender) {
                switch (sender.dialogResult) {
                    case 'submit':
                        alert('form submitted');
                        break;
                    case 'wj-hide-create':
                        break;
                }
            });
        });
        var dialog = wijmo.Control.getControl('#dialog');
        document.getElementById('btnInsert').addEventListener('click', function (e) {
            // show the dialog (modal window)
            dialog.show(true, function (sender) { });
        });
    </script>
}

CampusV4/Views/Sample/Input3.cshtml
@{
    var countries = new[] { "US", "Germany", "UK", "Japan", "Sweden", "Norway", "Denmark" };
    var coutriesMap = new object[countries.Length];
    for (var i = 0; i < countries.Length; i++)
    {
        coutriesMap[i] = new KeyValuePair<int, string>(i, countries[i]);
    }
}

<style>
    #popup label {
        padding: 0px;
    }

    #popup .btn {
        margin-bottom: 0px;
    }

    .wj-flexgrid {
        max-height: 200px;
        margin-bottom: 12px;
    }

    .modal-content {
        width: 400px;
    }
    /* style our custom 'edit buttons' */
    .wj-rowheaders .wj-cell .wj-glyph-pencil {
        opacity: .3;
        transform: scale(.5);
    }

    .wj-rowheaders .wj-cell:hover .wj-glyph-pencil {
        opacity: 1;
        color: #000080;
        transform: scale(1);
        transition: all linear 300ms;
    }

    /* wj-labeled-input: adapted from MDL styles */

    /* label input container */
    .wj-labeled-input {
        position: relative;
        font-size: 16px;
        display: inline-block;
        box-sizing: border-box;
        width: 300px;
        max-width: 100%;
        margin: 0 20px;
        padding: 20px 0;
    }

        /* Wijmo control in the container */
        .wj-labeled-input .wj-control.wj-content {
            margin: 0;
            width: 100%;
            background-color: transparent;
            border: none;
            border-bottom: 1px solid rgba(0,0,0,.1);
        }

            .wj-labeled-input .wj-control.wj-content button {
                opacity: 0.75;
                border-color: rgba(0,0,0,.1);
            }

        .wj-labeled-input .wj-input-group .wj-form-control {
            float: none;
        }

        /* label in the container (must come after the control) */
        .wj-labeled-input label {
            font-size: 16px;
            top: 24px;
            bottom: 0;
            margin: 0;
            pointer-events: none;
            position: absolute;
            display: block;
            width: 100%;
            overflow: hidden;
            white-space: nowrap;
            text-align: left;
            color: rgba(0, 0, 0, 0.258824);
            transition-duration: .2s;
            transition-timing-function: cubic-bezier(.4,0,.2,1);
        }

        /* move label out of the way when control is focused or not empty */
        .wj-static-labels .wj-labeled-input :not(.wj-state-focused) + label,
        .wj-labeled-input .wj-state-focused + label,
        .wj-labeled-input :not(.wj-state-empty) + label {
            font-size: 12px;
            top: 4px;
            color: rgb(63,81,181);
            visibility: visible;
        }

        .wj-labeled-input .wj-state-invalid + label {
            color: #d50000;
        }

        /* underline label */
        .wj-labeled-input label:after {
            background-color: rgb(63,81,181);
            bottom: 20px;
            content: '';
            height: 2px;
            left: 45%;
            position: absolute;
            transition-duration: .2s;
            transition-timing-function: cubic-bezier(.4,0,.2,1);
            visibility: hidden;
            width: 10px;
        }

        /* show underline when focused */
        .wj-labeled-input .wj-state-focused + label:after {
            left: 0;
            visibility: visible;
            width: 100%;
        }

        .wj-labeled-input .wj-state-invalid + label:after {
            background-color: #d50000;
        }

        /* validation message */
        .wj-labeled-input .wj-error {
            color: #d50000;
            position: absolute;
            font-size: 12px;
            margin-top: 3px;
            visibility: hidden;
            display: block;
        }

        .wj-labeled-input .wj-control.wj-state-invalid ~ .wj-error {
            visibility: visible;
        }
</style>

<div>
    <div class="page-title">
        <div class="title_left">
            <h3>ダイアログポップアップ呼出し</h3>
        </div>
    </div>
    <div class="clearfix"></div>
    <div class="row">
        <div class="col-md-12">
            <div class="x_panel">
                <div class="item form-group">
                    @(Html.C1().FlexGrid().Id("theGrid")
                                .IsReadOnly(true)
                                .AutoGenerateColumns(false)
                                .SelectionMode(C1.Web.Mvc.Grid.SelectionMode.Row)
                                .Columns(cols=>
                                {
                                    cols.Add().Binding("id").Header("ID").Width("50").IsReadOnly(true);
                                    cols.Add().Binding("country").Header("Country").DataMap(dm=>dm.Bind(coutriesMap).DisplayMemberPath("Value").SelectedValuePath("Value"));
                                    cols.Add().Binding("sales").Header("Sales").Format("n2");
                                    cols.Add().Binding("expenses").Header("Expenses").Format("n2");
                                })
                            )
                </div>
            </div>
        </div>
    </div>
</div>

<!-- the popup editor -->
<div id="popup" class="modal-content">
    <div class="modal-header">
        <button type="button" tabindex="-1" class="close wj-hide">
            <span>&times;</span>
        </button>
        <h4 class="modal-title">テスト<span id="item-id"></span></h4>
    </div>
    <div class="modal-body">
        <div class="wj-labeled-input">
            <input id="country" />
            <label for="country">テスト２</label>
            @Html.C1().ComboBox("#country").Bind(countries).SelectedIndex(countries.Length - 1)
        </div>
        <div class="wj-labeled-input">
            <input id="sales" />
            <label for="sales">テスト３</label>
            @Html.C1().InputNumber("#sales").Format("n2").Min(0).Step(100)
        </div>
        <div class="wj-labeled-input">
            <input id="expenses" />
            <label for="expenses">テスト４</label>
            @Html.C1().InputNumber("#expenses").Format("n2").Min(0).Step(100)
        </div>
        <div class="modal-footer">
            <button type="button" class="btn btn-primary wj-hide-ok">OK</button>
            <button type="button" class="btn btn-default wj-hide">キャンセル</button>
        </div>
    </div>
</div>
@Html.C1().Popup("#popup")

@section scripts{
    <script>
        c1.documentReady(function () {

            // create some random data
            var countries = 'US,Germany,UK,Japan,Sweden,Norway,Denmark'.split(',');
            var data = [];
            for (var i = 0; i < 100; i++) {
                data.push({
                    id: i,
                    country: countries[i % countries.length],
                    sales: Math.random() * 10000,
                    expenses: Math.random() * 5000,
                    overdue: (i + 1) % 4 == 0
                });
            }

            // the grid with custom editing behavior
            var theGrid = wijmo.Control.getControl('#theGrid');
            theGrid.itemsSource = data;

            // add 'edit button' to row header cells
            theGrid.formatItem.addHandler(function (s, e) {
                if (e.panel == s.rowHeaders && e.col == 0) {
                    e.cell.innerHTML = '<span class="wj-glyph-pencil"></span>';
                }
            });

            // handle button clicks
            theGrid.addEventListener(theGrid.hostElement, 'click', function (e) {
                var ht = theGrid.hitTest(e);
                if (ht.panel == theGrid.rowHeaders) {

                    // prepare form
                    var item = theGrid.rows[ht.row].dataItem;
                    formControls.itemId.textContent = item.id;
                    formControls.country.text = item.country;
                    formControls.sales.value = item.sales;
                    formControls.expenses.value = item.expenses;

                    // show the form
                    formControls.popup.show(true, function (e) {
                        if (e.dialogResult == 'wj-hide-ok') {

                            // commit changes if the user pressed the OK button
                            theGrid.collectionView.editItem(item);
                            item.country = formControls.country.text;
                            item.sales = formControls.sales.value;
                            item.expenses = formControls.expenses.value;
                            theGrid.collectionView.commitEdit();
                        }

                        // return focus to the grid
                        theGrid.focus();
                    });
                }
            });

            // attach controls to input form
            var formControls = {
                popup: wijmo.Control.getControl('#popup'),
                itemId: document.getElementById('item-id'),
                country: wijmo.Control.getControl('#country'),
                sales: wijmo.Control.getControl('#sales'),
                expenses: wijmo.Control.getControl('#expenses'),
            };
        });
    </script>
}

CampusV4/Views/Sample/InquiryRegister.cshtml
<div>
    <div class="page-title">
        <div class="title_left">
            <h3>引合</h3>
        </div>
    </div>
    <div class="clearfix"></div>
    <div class="row">
        <div class="col-md-12">
            <div class="x_panel">
                @using (Html.BeginForm("Input1", "Sample", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
                {
                    @Html.AntiForgeryToken()
                    <p style="font-weight:bold;">登録しました（メッセージ枠）</p>
                    <p style="font-weight:bold;"><u>[受注入力]</u></p>
                    <div class="form-group">
                        <label class="col-md-1 control-label" for="Text1">受注番号</label>
                        <div class="col-md-2">
                            <input class="form-control" id="Text1" name="Text1" type="text" />
                        </div>
                        <label class="col-md-1 control-label" for="Text2">引合番号</label>
                        <div class="col-md-2">
                            <input class="form-control" id="Text2" name="Text2" type="text" />
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-md-1 control-label" for="Text3">受注日</label>
                        <div class="col-md-3">
                            @Html.C1().InputDate().Id("Text3")
                        </div>
                        <label class="col-md-2 control-label" for="Text4">不具合製番</label>
                        <div class="col-md-4">
                            <input class="form-control" id="Text4" name="Text4" type="text" />
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-md-1 control-label" for="Text5">稟議番号</label>
                        <div class="col-md-2">
                            <input class="form-control" id="Text5" name="Text5" type="text" />
                        </div>
                        <label class="col-md-1 control-label" for="Text6">納期</label>
                        <div class="col-md-3">
                            @Html.C1().InputDate().Id("Text6")
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-md-1 control-label" for="Select1">分類記号</label>
                        <div class="col-md-1">
                            <select class="form-control" id="Select1" name="Select1">
                            </select>
                        </div>
                        <label class="col-md-1 control-label" for="Text6">纏め製番</label>
                        <div class="col-md-4">
                            <input class="form-control" id="Text6" name="Text6" type="text" />
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-md-1 control-label" for="Text7">注文番号</label>
                        <div class="col-md-4">
                            <input class="form-control" id="Text7" name="Text7" type="text" />
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-md-2 control-label" for="Select2">営業担当者</label>
                        <div class="col-md-2">
                            <select class="form-control" id="Select2" name="Select2">
                            </select>
                        </div>
                        <div class="col-md-4">
                            <input class="form-control" id="Text8" name="Text8" type="text" />
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-md-2 control-label" for="Select3">調達担当者</label>
                        <div class="col-md-2">
                            <select class="form-control" id="Select3" name="Select3">
                            </select>
                        </div>
                        <div class="col-md-4">
                            <input class="form-control" id="Text9" name="Text9" type="text" />
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-md-offset-2 col-md-2">
                            <div class="checkbox">
                                <label>
                                    <input type="checkbox" value="test" />内示
                                </label>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <label class="control-label">先行手配（</label>
                            <label>
                                <input type="radio" name="Radio1" value="test" /> 有り
                            </label>
                            <label>
                                <input type="radio" name="Radio1" value="test" /> 無し
                            </label>
                            <label class="control-label">）</label>
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-md-offset-2 col-md-2">
                            <div class="checkbox">
                                <label>
                                    <input type="checkbox" value="test" />キャンセル
                                </label>
                            </div>
                        </div>
                        <div class="col-md-3">
                            @Html.C1().InputDate().Id("Text10")
                        </div>
                    </div>
                    <div class="form-group">

                    </div>
                    <div class="form-group">

                    </div>
                    <div class="form-group">

                    </div>
                    <div class="ln_solid"></div>
                    <div class="item form-group">
                        <div class="col-md-6 col-sm-6 col-md-offset-3">
                            <a href="@Url.Action("Input2")" class="btn btn-primary">製番明細</a>
                            <a href="#" class="btn btn-primary">検収明細</a>
                            <a href="#" class="btn btn-primary">登録</a>
                        </div>
                    </div>
                }
            </div>
        </div>
    </div>
</div>

CampusV4/Views/Sample/SampleDialog.cshtml
<div class="modal fade" id="exampleModalToggle" aria-hidden="true" aria-labelledby="exampleModalToggleLabel" tabindex="-1">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalToggleLabel">Modal 1</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                Show a second modal and hide this one with the button below.
            </div>
            <div class="modal-footer">
                <button class="btn btn-primary" data-bs-target="#exampleModalToggle2" data-bs-toggle="modal" data-bs-dismiss="modal">Open second modal</button>
            </div>
        </div>
    </div>
</div>
<div class="modal fade" id="exampleModalToggle2" aria-hidden="true" aria-labelledby="exampleModalToggleLabel2" tabindex="-1">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalToggleLabel2">Modal 2</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                Hide this modal and show the first with the button below.
            </div>
            <div class="modal-footer">
                <button class="btn btn-primary" data-bs-target="#exampleModalToggle" data-bs-toggle="modal" data-bs-dismiss="modal">Back to first</button>
            </div>
        </div>
    </div>
</div>
<a class="btn btn-primary" data-bs-toggle="modal" href="#exampleModalToggle" role="button">Open first modal</a>